macro(returnOld keys pars)
    list(LENGTH keys ln)
    foreach(i in RANGE 0 ${ln})
        list(GET pars ${i} par)
        list(GET keys ${i} key)
        set(PARENT_SCOPE ${key} ${par})
    endforeach()
    return()
endmacro()